package PageUIs.nopcommerce.user;

public class UserCustomerInfoPageUI {
	public static final String ADDRESS_LINK = "xpath=//div[@class ='master-wrapper-content']//a[text()='Addresses']";
	public static final String GENDER_RADIO = "id=gender-female";
	public static final String FIRST_NAME_TEXTBOX = "id=FirstName";
	public static final String LAST_NAME_TEXTBOX = "id=LastName";
	public static final String DATE_OF_BIRTH_DAY_DROPDOWN_LIST = "css=select[name ='DateOfBirthDay']";
	public static final String DATE_OF_BIRTH_MONTH_DROPDOWN_LIST = "css=select[name ='DateOfBirthMonth']";
	public static final String DATE_OF_BIRTH_YEAR_DROPDOWN_LIST = "css=select[name ='DateOfBirthYear']";
	public static final String EMAIL_TEXTBOX = "css=input[id='Email']";
	public static final String COMPANY_TEXTBOX = "id=Company";
	public static final String SAVE_BUTTON = "id=save-info-button";
	public static final String POPUP = "css=span[class ='close']";
	public static final String CUSTOMER_INFO_LINK = "xpath=//a[text()='Customer info']";
	public static final String ADD_NEW_BUTTON = "xpath=//button[contains(@class,'add-address-button')]";
	public static final String ADD_FIRST_NAME_TEXTBOX = "id=Address_FirstName";
	public static final String ADD_LAST_NAME_TEXTBOX = "id=Address_LastName";
	public static final String ADD_EMAIL_TEXTBOX = "id=Address_Email";
	public static final String ADD_COUNTRY_DROPDOWN_LIST = "id=Address_CountryId";
	public static final String ADD_CITY_TEXTBOX = "id=Address_City";
	public static final String ADD_PHONE_NUMBER_TEXTBOX = "id=Address_PhoneNumber";
	public static final String ADD_ADDRESS_1_TEXTBOX = "id=Address_Address1";
	public static final String ADD_ZIP_POSTAL_CODE_TEXTBOX = "id=Address_ZipPostalCode";
	public static final String SAVE_ADDRESS_BUTTON = "xpath=//button[contains(@class,'save-address-button')]";
	public static final String TITLE_RESULT = "xpath=//div[@class='section address-item']//strong";
	public static final String ADD_NAME_UPDATED = "xpath=//li[@class = 'name']";
	public static final String ADD_EMAIL_UPDATED = "xpath=//li[@class = 'email']";
	public static final String ADD_PHONE_UPDATED = "xpath=//li[@class = 'phone']";
	public static final String ADD_ADDRESS1_UPDATED = "xpath=//li[@class = 'address1']";
	public static final String ADD_CITY_STATE_ZIP_UPDATED = "xpath=//li[@class = 'city-state-zip']";
	public static final String ADD_COUNTRY_UPDATED = "css=li[class = 'country']";
	public static final String ADD_SUCCESSFUL_NOTI_BAR = "xpath=//div[@class='bar-notification success']//p";
	public static final String ADD_SUCCESSFUL_NOTI_CLOSE_ICON = "xpath=//div[@class='bar-notification success']//span";
	public static final String CHANGE_PASSWORD_LINK = "xpath=//div[@class ='master-wrapper-content']//a[text()='Change password']";
	public static final String OLD_PASSWORD_TEXTBOX = "id=OldPassword";
	public static final String NEW_PASSWORD_TEXTBOX = "id=NewPassword";
	public static final String CONFIRM_NEW_PASSWORD_TEXTBOX = "id=ConfirmNewPassword";
	public static final String CHANGE_PASSWORD_BUTTON = "xpath=//button[contains(@class,'change-password-button')]";
	public static final String SUCCESSFUL_NOTIFICATION_BAR = "xpath=//p[text()='Password was changed']";
	public static final String SUCCESSFUL_NOTIFICATION_CLOSE_ICON = "xpath=//span[@class='close']";
	public static final String LOGOUT_LINK = "css=a[class='ico-logout']";
	public static final String PRODUCT_LIST_COMPUTERS_LINK = "xpath=//ul[@class='top-menu notmobile']//a[text()='Computers ']";
	public static final String PRODUCT_DESKTOP_LINK = "xpath=//h2[@class='title']//a[text()=' Desktops ']";
	public static final String MY_PRODUCT_REVIEW_LINK = "xpath=//a[text()='My product reviews']";
	public static final String MY_PRODUCT_REVIEW_TITLE_TEXT = "css=div[class='review-title']//strong";
	public static final String MY_PRODUCT_REVIEW_BODY_TEXT = "css=div[class='review-text']";
	public static final String SUCCESS_MESSAGE_UPDATE_CUSTOMER_INFO = "xpath=//p[text()='The customer info has been updated successfully.']";
}
